In [4]:
# importing pandas and numpy
import pandas as pd
import numpy as np

# crete a sample dataframe
data = pd.DataFrame({
    'age' :     [ 10, 22, 13, 21, 12, 11, 17],
    'section' : [ 'A', 'B', 'C', 'B', 'B', 'A', 'A'],
    'city' :    [ 'Gurgaon', 'Delhi', 'Mumbai', 'Delhi', 'Mumbai', 'Delhi', 'Mumbai'],
    'gender' :  [ 'M', 'F', 'F', 'M', 'M', 'M', 'F'],
    'favourite_color' : [ 'red', np.nan, 'yellow', np.nan, 'black', 'green', 'red']
})

# view the data
data

   age section     city gender favourite_color
0   10       A  Gurgaon      M             red
1   22       B    Delhi      F             NaN
2   13       C   Mumbai      F          yellow
3   21       B    Delhi      M             NaN
4   12       B   Mumbai      M           black
5   11       A    Delhi      M           green
6   17       A   Mumbai      F             red

In [7]:

# select all rows with a condition
print("\n\nData with age greater than 15\n\n")
data.loc[data.age >= 15]

Data with age greater than 15

   age section    city gender favourite_color
1   22       B   Delhi      F             NaN
3   21       B   Delhi      M             NaN
6   17       A  Mumbai      F             red

In [11]:
# select with multiple conditions
data.loc[(data.age>=12) & (data.gender == 'M')]

   age section    city gender favourite_color
3   21       B   Delhi      M             NaN
4   12       B  Mumbai      M           black

In [12]:
#Slice
data.loc[1:3]

   age section    city gender favourite_color
1   22       B   Delhi      F             NaN
2   13       C  Mumbai      F          yellow
3   21       B   Delhi      M             NaN

In [13]:
# select few columns with a condition
data.loc[(data.age >=12), ['city', 'gender']]

     city gender
1   Delhi      F
2  Mumbai      F
3   Delhi      M
4  Mumbai      M
6  Mumbai      F

In [14]:
# update a column with condition
data.loc[(data.age >= 12), ['section']] = 'M'
data

   age section     city gender favourite_color
0   10       A  Gurgaon      M             red
1   22       M    Delhi      F             NaN
2   13       M   Mumbai      F          yellow
3   21       M    Delhi      M             NaN
4   12       M   Mumbai      M           black
5   11       A    Delhi      M           green
6   17       M   Mumbai      F             red

In [18]:
# In this example, if the value in the column age is greater than 20, 
# then the loc function will update the values in the column section with “S” 
# and the values in the column city with Pune:

# update multiple columns with condition
data.loc[(data.age >= 20), ['section', 'city']] = ['S','Pune']
data

   age section     city gender favourite_color
0   10       A  Gurgaon      M             red
1   22       S     Pune      F             NaN
2   13       M   Mumbai      F          yellow
3   21       S     Pune      M             NaN
4   12       M   Mumbai      M           black
5   11       A    Delhi      M           green
6   17       M   Mumbai      F             red

In [19]:

# select rows with indexes
data.iloc[[0,2]]

   age section     city gender favourite_color
0   10       A  Gurgaon      M             red
2   13       M   Mumbai      F          yellow

In [20]:
# select rows with particular indexes and particular columns
data.iloc[[0,2],[1,3]] # the first pair is the indexes and the second one, the columns

  section gender
0       A      M
2       M      F

In [21]:
# select a range of rows
data.iloc[1:3]

   age section    city gender favourite_color
1   22       S    Pune      F             NaN
2   13       M  Mumbai      F          yellow

In [22]:
# select a range of rows and columns
data.iloc[1:3,2:4]

     city gender
1    Pune      F
2  Mumbai      F